services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: microservicio-java-backend:latest
    container_name: valdezbaluarte.pt-backend-1
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - dev-network
    depends_on:
      postgres-db: # <--- Ahora espera al nuevo nombre
        condition: service_healthy

  postgres-db: # <--- Renombrado de 'db' a 'postgres-db'
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  postgres_data:
    name: dev_postgres_data